SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
BASE_DIR="$( dirname "$SCRIPT_DIR" )"
CONFIG_FILE="$SCRIPT_DIR/../scan.config"
source "$BASE_DIR/system/env_system.sh"
source "$BASE_DIR/utils/health_check.sh"
print_message "[i]" "Backend health" "Backend health check succeeded"