SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
BASE_DIR="$( dirname "$SCRIPT_DIR" )"
CONFIG_FILE="$SCRIPT_DIR/../scan.config"
source "$BASE_DIR/system/config.sh"
source "$BASE_DIR/system/env_system.sh"

echo "==============================================="
echo "          PatchHound - by BBlue530"
echo "          Version: $PATCHHOUND_VERSION"
echo "==============================================="

source "$BASE_DIR/system/env_variables_scan.sh"
source "$BASE_DIR/system/config.sh"
source "$BASE_DIR/utils/health_check.sh"
source "$BASE_DIR/system/deps.sh"
source "$BASE_DIR/scan/sast_scan.sh"
source "$BASE_DIR/scan/trivy_scan.sh"
source "$BASE_DIR/scan/sbom_generate.sh"
source "$BASE_DIR/scan/sbom_upload.sh"
source "$BASE_DIR/system/vulns_found.sh"
source "$BASE_DIR/display/scan_results.sh"
source "$BASE_DIR/display/conclusion.sh"

print_message "[+]" "Scan result" "Scan finished successfully"