REPO_DIR="."
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
CONFIG_FILE="$SCRIPT_DIR/../scan.config"

source "$(dirname "$0")/system/env_variables_scan.sh"
source "$(dirname "$0")/system/config.sh"
source "$(dirname "$0")/utils/health_check.sh"
source "$(dirname "$0")/system/deps.sh"
source "$(dirname "$0")/scan/sast_scan.sh"
source "$(dirname "$0")/scan/trivy_scan.sh"
source "$(dirname "$0")/scan/sbom_generate.sh"
source "$(dirname "$0")/scan/sbom_upload.sh"
source "$(dirname "$0")/display/scan_results.sh"
source "$(dirname "$0")/system/vulns_found.sh"
source "$(dirname "$0")/display/conclusion.sh"

echo "[+] Scan Finished"