name: PatchHound Pipeline

on:
  workflow_call:
    secrets:
      BASE_URL:
        required: true
      ALERT_WEBHOOK:
        required: true
      TOKEN:
        required: true

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install PatchHound
        run: |
          cd PatchHound
          chmod +x install.sh
          ./install.sh

      - name: Configure PatchHound
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ALERT_WEBHOOK: ${{ secrets.ALERT_WEBHOOK }}
        run: patchhound config --set-secret BASE_URL "$BASE_URL" ALERT_WEBHOOK "$ALERT_WEBHOOK"

      - name: Run SBOM Scan
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: patchhound scan --token "$TOKEN"

      - name: Upload vulnerability summary
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-summary
          path: |
            summary.md
            sbom.cyclonedx.json
            vulns.cyclonedx.json
            prio_vulns.json
            sast_report.json
            trivy_report.json
            path_to_resources_token.txt