name: Secure Pipeline

on:
  push:
    branches: [master]

jobs:
  security-check:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      COMMIT_SHA: ${{ github.sha }}
      AUTHOR_NAME: ${{ github.actor }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v3
          
      - name: Run SBOM Scan script
        run: |
          chmod +x ./scan.sh
          ./scan.sh scan.config
      
      - name: Upload vulnerability summary
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-summary
          path: |
            summary.md
            sbom.cyclonedx.json
            vulns.cyclonedx.json
            prio_vulns.json